project:
  type: website

website:
  title: "David T. Watkeys"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: research.qmd
        text: Research
        
      - href: papers.qmd
        text: Papers
        
      - href: socialmedia.qmd
        text: Social Media
        
      - href: cv.qmd
        text: CV
        
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


