project:
  type: website

website:
  title: "David T. Watkeys"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: research.qmd
        text: Research
        
      - href: papers.qmd
        text: Papers
        
      - href: socialmedia.qmd
        text: Public History Media
        
      - href: cv.qmd
        text: CV
        
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


# 4/13/2026 - got the site up - got headers in place so skeleton is done. 
              ##still need to download VA census data for ggplot use
              
              ##need to fill in one page at a time. CV & Resume are most
              ##available, so start with those and papers and social media 
              ##can be filled with drafts. - Mark Draft - 
              
              ## "research" will be census & Bibliography 
              ## edit title to "research and Bibliography?"
              ## can I transfer my last site to this???
              
